[package]
name = "splitdesk-client-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "SplitDesk Linux client"

[[bin]]
name = "splitdesk-client-linux"
path = "src/main.rs"

[dependencies]
splitdesk-client.workspace = true
tokio.workspace = true
